//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spike.Consumer.UserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IUserProvider")]
    public interface IUserProvider {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProvider/AddUser", ReplyAction="http://tempuri.org/IUserProvider/AddUserResponse")]
        Spike.Contracts.Users.User AddUser(Spike.Contracts.Users.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProvider/AddUser", ReplyAction="http://tempuri.org/IUserProvider/AddUserResponse")]
        System.Threading.Tasks.Task<Spike.Contracts.Users.User> AddUserAsync(Spike.Contracts.Users.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProvider/GetUser", ReplyAction="http://tempuri.org/IUserProvider/GetUserResponse")]
        Spike.Contracts.Users.User GetUser(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProvider/GetUser", ReplyAction="http://tempuri.org/IUserProvider/GetUserResponse")]
        System.Threading.Tasks.Task<Spike.Contracts.Users.User> GetUserAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProvider/GetUsers", ReplyAction="http://tempuri.org/IUserProvider/GetUsersResponse")]
        Spike.Contracts.Users.User[] GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProvider/GetUsers", ReplyAction="http://tempuri.org/IUserProvider/GetUsersResponse")]
        System.Threading.Tasks.Task<Spike.Contracts.Users.User[]> GetUsersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserProviderChannel : Spike.Consumer.UserService.IUserProvider, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserProviderClient : System.ServiceModel.ClientBase<Spike.Consumer.UserService.IUserProvider>, Spike.Consumer.UserService.IUserProvider {
        
        public UserProviderClient() {
        }
        
        public UserProviderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserProviderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProviderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Spike.Contracts.Users.User AddUser(Spike.Contracts.Users.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public System.Threading.Tasks.Task<Spike.Contracts.Users.User> AddUserAsync(Spike.Contracts.Users.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public Spike.Contracts.Users.User GetUser(System.Guid id) {
            return base.Channel.GetUser(id);
        }
        
        public System.Threading.Tasks.Task<Spike.Contracts.Users.User> GetUserAsync(System.Guid id) {
            return base.Channel.GetUserAsync(id);
        }
        
        public Spike.Contracts.Users.User[] GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<Spike.Contracts.Users.User[]> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
    }
}
